# Fundamentals of NumPy

This notebook aims to quickly walk you through the most fundamental bits of NumPy, including:
1. how to create/initiate 1D arrays and 2D matrices,
2. how to get/set the shape of numpy arrays,
3. and how to calculate the dot product of two NumPy arrays, and take the norms.

*This notebook is created by cherry-picking from [the official documents of NumPy](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html). Please refer to that page for more information.*

In [2]:
import numpy as np

## 1. `ndarray` in NumPy

NumPy’s main object is the homogeneous multidimensional array (`ndarray`). It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.

A list of elements can be expressed as an `ndarray` of rank 1, i.e. a 1D array; a matrix can be expressed as an `ndarray` of rank 2.

Here lists some important attributes of `ndarray`:

* **`ndarray.ndim`**: the rank of the `ndarray`. For instance, a matrix has a rank of 2.
* **`ndarray.shape`**: the dimensions of the `ndarray` as a tuple of integers. For an array having 10 elements, the shape is `(10,)` (**note the trailing comma**, not the same as `(10, 1)`); for a matrix having 20 rows and 30 columns, the shape is `(20, 30)`.
* **`ndarray.size`**: the total number of elements in the `ndarray`, which is equal to the product of the dimensions.
* **`ndarray.dtype`**: an object describing the type of the elements in the array.

In [3]:
arr = np.array(range(1, 10))
print('arr\t\t', arr)
print('arr.ndim\t', arr.ndim)
print('arr.shape\t', arr.shape)
print('arr.size\t', arr.size)
print('arr.dtype\t', arr.dtype)

arr		 [1 2 3 4 5 6 7 8 9]
arr.ndim	 1
arr.shape	 (9,)
arr.size	 9
arr.dtype	 int64


In [4]:
arr.

SyntaxError: invalid syntax (<ipython-input-4-25a33d75fd04>, line 1)

## 2. Array Creation

There are several ways to create `ndarray`s.

### 2.1 Using the `array` function

You can create a 1D `ndarray` from an existing list/array easily using the `array` function.

In [ ]:
np.array([1, 2, 3, 4])

Note that there is only one argument. So never do this:

In [ ]:
np.array(1, 2, 3, 4)

To create a matrix, call `array` on a sequence of sequence.

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

In [ ]:
x.shape

### 2.2 Using `zeros`, `ones`, `empty`

When the contents of the array to be created are unknown, but its dimensions are known, use one of `zeros`, `ones`, `empty`.

In [ ]:
np.zeros((2, 3))  # the elements are explicitly initialized to zeros

In [ ]:
np.ones((2, 3))  # the elements are explicitly initialized to ones

In [ ]:
np.empty((2, 3))  # the elements are not explicitly initialized; expect random values

The default `dtype` is `numpy.float64` for these functions.

### 2.3 Using `arange`, `linspace`

Akin to `range` in Python, `arange` in NumPy returns a sequence of numbers in a `ndarray`. Use the `dtype` parameter to change the type, or use `astype()` function to cast into another type.  

In [ ]:
np.arange(1, 3, 0.2)

Due to the finite precision of floating point numbers, however, it's better to use `linspace` when we are trying to create a sequence of floating point numbers, specifying how many elements we want, instead of the `step`.

In [ ]:
np.linspace(1, 3, 7)

## 3. Playing with the Shapes of `ndarray`s

In [ ]:
arr = np.arange(1, 10)
arr

### 3.1 How to Get the Shape of an `ndarray`

In [ ]:
arr.shape

### 3.2 How to Reshape the `ndarray`:

In [ ]:
arr.reshape((3, 3))

The `reshape` function returns a new `ndarray` with the shape changed without modifying the original one.

In [ ]:
arr

In [ ]:
arr.reshape((9,1))

To directly modify the shape of an `ndarray`:

In [ ]:
arr.shape = (3, 3)
arr

Note that 1d arrays and 2d arrays are different. 

In [7]:
xx = arr.reshape((1,9))
xx

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
xx.shape

(1, 9)

In [12]:
xx[0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr.shape

(9,)

## 4. Basic Operations

### 4.1 Arithmetic Operators

Arithmetic operators on `ndarray`s apply elementwise (so the operation is *vectorized*). A new `ndarray` will be created to hold the result.

In [ ]:
arr = np.array([1, 2])

In [ ]:
arr + 1

In [ ]:
arr * 2

In [ ]:
arr ** 2

### 4.2 Dot Products

Given two `ndarray`s with proper shapes:

In [ ]:
a = np.array([1, 2])
a

In [ ]:
b = np.array([[1], [2]])
b

To calculate the dot product, the sentence in the following cell is intuitive but **WRONG**:

In [ ]:
a * b  # calculating elementwise product!

To correctly calculate the dot products of two `ndarray`s, use `numpy.dot` or the `dot` function on the `ndarray` object.

In [ ]:
a.dot(b)

In [ ]:
np.dot(a, b)

Both ways create a new `ndarray` to hold the results without modifying the original ones.

### 4.3 Norms

See https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html for more details. 

In [14]:
a = np.arange(3)-1
a

array([-1,  0,  1])

In [15]:
np.linalg.norm(a)

1.4142135623730951

In [16]:
np.linalg.norm(a, ord=1)

2.0

In [19]:
np.linalg.norm(a, ord=np.inf)

1.0